### PR TITLE
Add interoperability test between Gramine and rats-tls

### LINKED ISSUE #8: The interoperability testing between Gramine and rats-tls
Current testing model is: Gramine as client and attester vs rats-tls as server and verifier (mtls)

The rats-tls contains sample server program (see https://github.com/inclavare-containers/rats-tls/tree/master/samples for the source codes). 

At present, the sample server program doesn't run in a TEE, just in host, providing a self-signed TLS certificate.

---

For the local testing for the case "rats-tls as client and attester vs rats-tls as server and verifier (mtls)", simply run:

```
git clone https://github.com/inclavare-containers/rats-tls
cd rats-tls
cmake -DRATS_TLS_BUILD_MODE="host" -DBUILD_SAMPLES=on -H. -Bbuild
make -C build install
cd /usr/share/rats-tls/samples
RATS_TLS_GLOBAL_LOG_LEVEL=debug ./rats-tls-server --log-level debug --attester nullattester --verifier sgx_ecdsa --mutual
```

The client side command is:
```shell
./rats-tls-client --log-level debug --attester sgx_ecdsa --verifier nullverifier --mutual
```

By default, the listening port is 1234. -p option can be used to overwrite the default port.

### PR DESCRIPTION
**Pull request by KB5201314**
Closes #8

### CODE REVIEW

**Comment by KB5201314** [comment]
@shnwc @dimakuv @jiazhang0 Please feel free to provide any feedback or comments on this PR. Thanks!

**Comment by KB5201314** [comment]
The cert files have been updated with new CBOR tag values.

**Comment by dcmiddle** [comment]
thanks @KB5201314 !
fyi @dimakuv @shnwc

**Comment by shnwc** [comment]
Great job @KB5201314 and @dimakuv !

**Comment by dimakuv** [comment]
I checked:
1. Both certificates are correct (examined via `openssl x509 -in gramine-cert.pem -text -noout -certopt ext_parse`).
2. The description is correct:
    - Gramine description is definitely correct;
    - Occlum/RATS-TLS description looks fine, though I didn't test the steps.

I would amend the descriptions a bit, but the general flow is good. Anyway, the PR was already merged, so I won't nitpick.

**Comment by shnwc** [comment]
@dimakuv feel free to create a new PR to amend the description.

**Pull request merged**
